name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-and-deploy-staging:
    name: Call reusable workflow when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy-nox.yaml@main
    with:
      app_name: dcat-ap-no-validator-service
      python_version: "3.10"
      python_architecture: x64
      environment: staging
      cluster: digdir-fdk-dev
      nox_image: True
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
