name: Deploy to staging

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to staging environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install dependencies
        run: |
          pip install poetry==1.1.4
          pip install nox==2020.08.22
          pip install nox-poetry==0.5.0

      - name: Build image and test with nox
        run: nox
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          FUSEKI_PASSWORD: ${{ secrets.FUSEKI_PASSWORD }}

      - name: Tag and publish docker image to Google Cloud
        run: |
          docker tag eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service:test eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service:$GITHUB_SHA
          docker tag eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service:test eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service:staging_latest
          docker rmi eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service:test
          docker -- push eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/dcat-ap-no-validator-service
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/dcat-ap-no-validator-service:$GITHUB_SHA" -f ./helm/dcat-ap-no-validator-service/values/staging.yaml ./helm/dcat-ap-no-validator-service/ > ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          project_id: digdir-fdk-dev
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-dev

      - name: Deploy to staging
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Application: dcat-ap-no-validator-service | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
